# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [1]:
import numpy as np

In [14]:
# Create and solve the relevant system of equations

'''
Denote coffee as x
Denote tea as y

1.) 29x + 41y = 490
2.) 23x + 41y = 448
'''

# Define A and B:

A = np.matrix([[29, 41],[23, 41]])
B = np.matrix([[490, 448]])

# Transpose B to satisfy shape assumption (number of columns in B need to equal number of rows in A):

B = B.T

# Solve for x, y

x, y = np.linalg.solve(A, B)
x, y

(matrix([[7.]]), matrix([[7.]]))

In [ ]:
# Describe your result

# Coffee and tea cost the same amount! 7 dollars per bag.

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [11]:
# Create and solve the relevant system of equations

'''
Denote children as x
Denote adults as y

1.) 12x + 3y = 162
2.) 8x + 3y = 122
'''

# Define A and B:

A = np.matrix([[12, 3],[8, 3]])
B = np.matrix([[162, 122]])

# Transpose B to satisfy shape assumption (number of columns in B need to equal number of rows in A):

B = B.T

# Solve for x, y

x = np.linalg.solve(A, B)
x

matrix([[10.],
        [14.]])

In [13]:
8*10 + 3*14

122

In [ ]:
# Describe your result

# Childrens' tickets cost $10, and adults' cost $14.

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [19]:
(-2) + (-1)

-3

In [25]:
# Create and solve the relevant system of equations

'''
Denote onions as x
Denote tomatoes as y
Denote carrots as z

1.) x + y + z = 7
2.) 0.5x + 0.75y + 1.25z = 5.25
3.) 
'''

#  t  = 2o which is equal to: -2o + 1t + 0c = 0
   

# Define A and B:

A = np.matrix([[1,1,1],[.5,.75,1.25],[-2,1,0]])
B = np.matrix([[7, 5.25, 0]])

# Calculate inverse of A and take the dot product
A_inv = np.linalg.inv(A)
X = A_inv.dot(B.T)
print (X)

# Solve for x, y

x = np.linalg.solve(A, B.T)
x

[[2.]
 [4.]
 [1.]]


matrix([[2.],
        [4.],
        [1.]])

In [ ]:
# Describe your result

# 2 onion, 4 tomatoes and one carrot

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [30]:
# Create and solve the relevant system of equations

'''

A.) x + y + z = 1240
B.) .10x + .20y + .30z = 276
C.) z = 2x or -2x + z + 0y = 0

'''

# Define A and B:

A = np.matrix([[1,1,1],[.1,.2,.3],[-2,0,1]])
B = np.matrix([[1240, 276, 0]])

# Calculate inverse of A and take the dot product
A_inv = np.linalg.inv(A)
X = A_inv.dot(B.T)
print (X)

# Solve for x, y

x = np.linalg.solve(A, B.T)
x

[[280.]
 [400.]
 [560.]]


matrix([[280.],
        [400.],
        [560.]])

In [28]:
.10*280 + .20*400 + .3*560

276.0

In [ ]:
# Describe your result

# 1BR = $280/month, 2BR = $400/month, 3BR = $560/month

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 